### ISSUE TITLE
Video preview doesn't scale on larger and smaller screens

### ISSUE THREAD

**Issue by rioforce** [BiMStop/Biscuit#10]
The position of the video preview is small and just stays in the same place.

**Comment by lunears** [comment]
This is being worked on and will be dynamic.

**Comment by lunears** [comment]
Can I have a screenshot of the bug?

**Comment by lunears** [comment]
What exactly do you mean by larger and smaller screens?  Is it when you resize the window?

**Comment by rioforce** [comment]
Yes, when I resize the window. On 1080p screens the video preview looks pretty small there too, because the window size is larger.

**Comment by lunears** [comment]
The windows actually isn't meant to be resized at this time, but eventually I will fix that.

**Comment by lunears** [comment]
This might be fixed in a previous commit, but I have not tested it.

**Comment by lunears** [comment]
Fixed in latest commit.
