### ISSUE TITLE
Going back to the home page resets my animation

### ISSUE THREAD

**Issue by rioforce** [BiMStop/Biscuit#11]
If I capture frames, and click Home, it deletes all of my frames and starts fresh

**Comment by lunears** [comment]
This should be fixed in the latest commit, but I have not tested it; also frames should be exported but will not show in the frame preview.  As a side effect of this, frames will not be lost on program close, but will be fixed before release.

**Comment by lunears** [comment]
The issue stated in my comment above should be fixed in this latest commit (still not tested).
